########################### PACKAGES TO INSTALL AND LOAD ############################################



# install.packages("shinymaterial")

# conflicted::conflict_prefer(name = "select", winner = "dplyr")
# conflicted::conflict_prefer(name = "box", winner = "shinydashboard")
# devtools::install_github("ricardo-bion/ggradar")
library("shinydashboard")
library("shiny")
library("pkgload")
library(GGally)
library("tidyverse")
library("ggplot2")
# library(rmapshaper)
library("leaflet")
library("DT")
library(fmsb)
library("ggiraphExtra")# library(conflicted)
library("ggcorrplot")
library("viridis")
library("leaflet.extras")
library("leaflet.extras2")
library("stringr")
library("readxl")
library("shinymaterial")
library("shinyWidgets")
library("shinycssloaders")
library("superheat")
library("shinyjs")
library("shinyalert")
library("ggnewscale")
# install.packages("ggnewscale")
library("bslib")
library("shinyBS")
library("plotly")
library("ggrepel")
library("kableExtra")
library("sp")
library("sf")
library("cowplot")

########################## PACKAGES TO INSTALL AND LOAD ##################################################

